# Set color defaults
setw -g clock-mode-colour                 "#95cdf7"

set -gq @thm_bg                           "#101417"
set -gq @thm_bar_bg                       "#262a2e"
set -gq @thm_bar1_bg                      "#95cdf7"
set -gq @thm_bar1_fg                      "#00344e"
set -gq @thm_fg                           "#e0e3e8"
set -gq @thm_primary                      "#95cdf7"
set -gq @thm_inverse_primary              "#266489"
set -gq @thm_surface_low                  "#181c20"
set -gq @thm_surface                      "#1c2024"
set -gq @thm_surface_variant              "#262a2e"
set -gq @thm_outline                      "#41474d"
set -gq @thm_text_variant                 "#c1c7ce"
