# ┌┬┐┌┬┐┬ ┬─┐ ┬
#  │ ││││ │┌┴┬┘
#  ┴ ┴ ┴└─┘┴ └─

# Change prefix from default Ctrl+b to Ctrl+a (easier to reach)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v

# reload config filer
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded..."

# Start window and pane numbering at 1 instead of 0 (matches keyboard layout)
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# don't rename windows automatically
set-option -g allow-rename off

# Enable mouse mode (click to change panes, drag to resize)
set -g mouse on

# Increase scrollback history limit
set -g history-limit 100000

# Fix the Esc key delay issue when using Vim/Neovim
set -s escape-time 10

# Enable OSC 52 clipboard sequences
set -s copy-command 'wl-copy'

set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ',xterm-kitty:cnorm=\E[?12h\E[?25h:Ss=\E[%p1%d q:Se=\E[2 q'

# Theme

# Source matugen
source-file ~/.config/tmux/default.conf
set -g window-active-style "bg=#{@thm_bg} fg=#{@thm_fg}"


BEV_NW="◖"
BEV_NE="◗"
BEV_SE="◗"
BEV_SW="◖"

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none


# Panes
set -g pane-border-style "fg=#{@thm_primary}"
set -g pane-active-border-style "fg=#{@thm_primary}"

# Statusbar

set -g status off
set -g status-position bottom
set -g status-justify absolute-centre
set -g status-style "bg=#{@thm_bg} fg=#{@thm_fg}"

# Left
set -g status-left "\
#[fg=#{@thm_bar1_fg} bg=#{@thm_bar1_bg},bold] #S\
#[fg=#{@thm_bar1_bg} bg=#{@thm_bg}]${BEV_NE}\
"
set -g status-left-length 25

# Right
set -g status-right "\
#[fg=#{@thm_bar1_bg} bg=#{@thm_bg}]◖\
#[fg=#{@thm_bar1_fg} bg=#{@thm_bar1_bg},bold]#(whoami | tr "[:lower:]" "[:upper:]")\
#[fg=#{@thm_bg} bg=#{@thm_bar1_bg}]@\
#[fg=#{@thm_bar1_fg} bg=#{@thm_bar1_bg},bold]#(hostname | tr "[:lower:]" "[:upper:]") \
"
set -g status-right-length 50

# Center
setw -g window-status-format "\
#[fg=#{@thm_fg} bg=#{@thm_bg}] #I\
·\
#W \
"

setw -g window-status-current-format "\
#[fg=#{@thm_outline} bg=#{@thm_bg}]${BEV_NW}\
#[fg=#{@thm_primary} bg=#{@thm_outline}]#I\
#[fg=#{@thm_fg} bg=#{@thm_outline}]·\
#[fg=#{@thm_primary} bg=#{@thm_outline}]#W\
#[fg=#{@thm_outline} bg=#{@thm_bg}]${BEV_SE}\
"
setw -g window-status-separator "//"

# Bell style?
setw -g window-status-bell-style "fg=#{@thm_inverse_primary} bg=#{@thm_text_variant}"

# Messages
set -g message-style "fg=#{@thm_primary} bg=#{@thm_bg}"

